### ISSUE TITLE
Unable to download songs on windows

### ISSUE THREAD

**Issue by vishnukannaujia** [ankitmathur3193/song-cli#1]
Add this as a requirement 
C:\Users\Vishnu Kannaujia\Downloads>song -d tere bina
Downloading page https://www.google.co.in/search?q=tere+bina+mr+jatt ..
Downloading page https://mr-jatt.com/album/single-tracks-songs/monty-tere-bina-ygdx.html ..
Downloading in 320 kbps
Downloading file Tere Bina-(Mr-Jatt.com).mp3
'wget' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ankitmathur3193** [comment]
Try it on ubuntu...:p.

**Comment by ankitmathur3193** [comment]
Now working on windows also..
