### ISSUE TITLE
Option to download all

### ISSUE THREAD

**Issue by jotyGill** [ankitmathur3193/song-cli#4]
Hi There,
After searching for, lets say a singer's name, currently it only shows the songs. It would be great if you could also download all of those songs at once. Cheers. :)

**Comment by ankitmathur3193** [comment]
Hi jotyGill,
I have added option for downloading all songs at once. Cheers :)
To use that option ,you need to upgrade song-cli to version 2.9 by running
pip install --upgrade song

For downloading all songs
song  -d  --download-all  sunidhi chauhan
![download_all](https://cloud.githubusercontent.com/assets/15183662/26557512/98b8ebee-44bf-11e7-832d-da724a3e55a3.png)
