### ISSUE TITLE
TypeError: tuple indices must be integers, not str

### ISSUE THREAD

**Issue by ghost** [ankitmathur3193/song-cli#6]
![song err](https://cloud.githubusercontent.com/assets/7684699/26603586/9b8dfe0e-4587-11e7-9b47-c40b2086e4a8.png)

**Comment by ankitmathur3193** [comment]
Resolved it in the latest version...
Do "pip install --upgrade song",
It was occurring due to old version of Beautifulsoup installed on your pc.
Now I have mentioned in the setup file,which version is needed for my script
